//! Strategy module (Phase 3.2 start — smallest viable skeleton per approved transfer plan).
//!
//! Multi-signal fusion foundation: processors (trait) produce Decimal-based signals;
//! FusionEngine combines them with attribution for journal + Hermes closed-loop learning.
//!
//! **Wiki-first compliance**: All design/credits in wiki/strategies/multi-signal-fusion.md,
//! integrations/polymarket-apis-and-data-sources.md, decisions/2026-05-25-adopt-multi-signal-fusion-from-btc-bot.md,
//! concepts/hermes-self-improvement.md (new fusion section), docs/project-plan.md (3.1-3.5), log.md top entry (2026-05-25 fees impl prepend).
//! Explicit credits to Polymarket-BTC-15-Minute-Trading-Bot/core/strategy_brain/{fusion_engine/signal_fusion.py,
//! signal_processors/base_processor.py + siblings} + openclaw-ai-polymarket-trading-bot/src/engine/{features,predictor,llmScorer}.ts
//! + poly-maker/poly_data/* + Poly-Trader/polymarket_ai_*.py + agents/agents/polymarket/*.
//!
//! Net-of-fees + DecisionReport extension credits: wiki/strategies/fees-tax-latency-and-execution-tiers.md + goals-and-operational-cadence.md (efe1660).
//!
//! **Exact patterns followed (no deviations)**:
//! - rust_decimal::Decimal for *all* scores, edges, math (Cargo.toml + AGENTS.md: "never float for finance").
//! - anyhow::Result + tracing (info/warn) for errors (see src/ingester/mod.rs ingest_tick).
//! - sqlx/journal hooks commented for future attribution writes (see src/journal/{models.rs,writer.rs} Reflection + INSERT patterns; existing tables only, no migrations).
//! - Heavy risk comments on every trading-related item (AGENTS: "All trading-related code must be heavily commented with risk implications").
//! - Paper-only (no real paths, no SDK, no wallet). Preserves all verified (k8s-apply, hermes ts, subpath, probes, JSON, Phase 2 SSR, fmt/clippy).
//! - No new deps, no new DB tables, no behavior change to ingester/paper/ui/hermes.
//! - Smallest: 1-2 processor stubs + basic FusionEngine (no full impl, no tests here — expanded per follow-ups per anti-pattern #2 briefing). Net edge extension is the minimal addition for fees wiki requirement.
//!
//! **Risk note (repeated for audit)**: This is paper-only scaffolding. Real capital exposure requires explicit human gates (AGENTS safety #1-5). Fusion signals can correlate or overfit; attribution depends on complete journal (log warnings, never silent). All P&L/edges use Decimal exclusively.

// Allow dead_code for this minimal skeleton (unused until wired in follow-up increments per plan; full usage + tests in later phases to avoid anti-pattern #2).
// This is the smallest change delivering the artifact (trait + 2 processors + FusionEngine + attribution) while satisfying fmt/clippy -D warnings + AGENTS.
#![allow(dead_code)]

use anyhow::Result;
use rust_decimal::Decimal;
use rust_decimal_macros::dec;
use serde_json::json;
use tracing::warn;

/// Normalized signal from a processor (inspired by BTC bot base_processor.py Signal + confidence/edge).
/// All values Decimal; metadata for attribution (e.g. which sub-features fired).
#[derive(Debug, Clone)]
pub struct Signal {
    pub processor_name: &'static str,
    pub score: Decimal,        // e.g. -1.0..1.0 edge direction
    pub confidence: Decimal,   // 0.0..1.0
    pub edge: Option<Decimal>, // expected value or similar (Decimal)
    pub metadata: serde_json::Value,
}

/// Minimal fee context for net-of-fees calculations in fusion (decoupled from paper crate for skeleton).
/// Values from PaperTradingEngine::fee_model() or conservative defaults.
/// See wiki/strategies/fees-tax-latency-and-execution-tiers.md for why net (not gross) is mandatory.
#[derive(Debug, Clone, Default)]
pub struct FeeContext {
    pub taker_bps: Decimal,
    pub maker_bps: Decimal,
    pub est_gas_usdc: Decimal,
    pub rewards_offset_bps: Decimal,
}

/// Decision Report (for 5-min deliberate tier + journal).
/// Exposes **net edge after fees** as the primary signal (per approved tiers + cadence wiki pages).
/// Attribution includes per-signal + fee_impact breakdown for Hermes (3.3).
/// Smallest: no chrono timestamp (avoids dep); generated by caller if needed.
/// RISK: Consumers *must* gate on net_edge (min 4-6% per goals wiki); gross edge leads to negative expectancy at $150 scale after fees.
#[derive(Debug, Clone)]
pub struct DecisionReport {
    pub fused_gross_edge: Decimal,
    pub net_edge_after_fees: Decimal,
    pub confidence: Decimal,
    /// Full attribution (per processor + fee_impact + metadata). Store as jsonb in journal.decision_context or metrics.
    pub attribution: serde_json::Value,
    // future: opportunities: Vec<...>, risk_checks: ...
}

/// Trait for signal processors (port of base_processor.py + siblings).
/// Implementations must be pure or read-only on snapshots; no side effects.
/// Risk: Processor bugs can inject bad signals into fusion -> bad paper decisions.
/// Mitigation: paper-only, journal every output, Hermes post-resolution attribution + anomaly detection.
pub trait SignalProcessor: Send + Sync {
    fn name(&self) -> &'static str;

    /// Compute signal from current market snapshot + context.
    /// In real use: fed by ingester events (orderbook jsonb + mids as Decimal).
    fn compute_signal(
        &self,
        _market_snapshot: &serde_json::Value,
        _ctx: &serde_json::Value,
    ) -> Result<Signal>;
}

/// Stub 1: Orderbook / momentum processor (short-horizon from openclaw + BTC orderbook/tick_velocity).
/// Minimal: derives simple imbalance from hypothetical snapshot (extend later with real OrderbookSnapshot).
/// Risk: Momentum reverses at resolution; thin books produce noisy signals. Always combine with liquidity filter (see market-making-liquidity.md).
pub struct OrderbookMomentumProcessor;

impl SignalProcessor for OrderbookMomentumProcessor {
    fn name(&self) -> &'static str {
        "orderbook_momentum"
    }

    fn compute_signal(
        &self,
        _snapshot: &serde_json::Value,
        _ctx: &serde_json::Value,
    ) -> Result<Signal> {
        // Placeholder logic (real: parse bids/asks jsonb from ingester, compute imbalance/velocity as Decimal).
        // For skeleton: neutral with low confidence.
        let score = Decimal::ZERO;
        let confidence = Decimal::from(10) / Decimal::from(100); // 0.10 (magic per skeleton; extracted const attempt hit rust_decimal const / limitation under clippy -D; see fix round in review)
        warn!(processor = %self.name(), "stub processor (paper-only; extend with real snapshot parsing + Decimal math)");
        Ok(Signal {
            processor_name: self.name(),
            score,
            confidence,
            edge: Some(score * confidence),
            metadata: json!({"stub": true, "inspired_by": "openclaw/features + BTC orderbook_processor + tick_velocity"}),
        })
    }
}

/// Stub 2: Simple spike / divergence (from BTC spike_detector + divergence_processor).
/// Risk: Spikes can be news-driven or manipulation; false positives lead to over-trading in paper (still virtual loss of opportunity).
pub struct SpikeDivergenceProcessor;

impl SignalProcessor for SpikeDivergenceProcessor {
    fn name(&self) -> &'static str {
        "spike_divergence"
    }

    fn compute_signal(
        &self,
        _snapshot: &serde_json::Value,
        _ctx: &serde_json::Value,
    ) -> Result<Signal> {
        let score = Decimal::ZERO;
        let confidence = Decimal::from(5) / Decimal::from(100); // 0.05 stub (magic per skeleton; extracted const attempt hit rust_decimal const / limitation under clippy -D; see fix round in review; added warn for consistency per review)
        warn!(processor = %self.name(), "stub processor (paper-only; extend with real snapshot parsing + Decimal math)");
        Ok(Signal {
            processor_name: self.name(),
            score,
            confidence,
            edge: Some(score * confidence),
            metadata: json!({"stub": true, "inspired_by": "BTC spike_detector + divergence_processor"}),
        })
    }
}

/// Basic FusionEngine (port of BTC signal_fusion.py).
/// Owns processors; fuse() returns aggregated + per-signal attribution for journal/Hermes.
/// Current impl: simple weighted average (extensible to consensus/divergence rules).
/// Risk: Poor weights or unhandled correlation amplifies drawdowns in paper (virtual). Always journal full attribution.
/// Mitigation: paper-only; Hermes 3.3 closed-loop will measure real P&L per signal and propose weight changes (gated).
pub struct FusionEngine {
    processors: Vec<Box<dyn SignalProcessor>>,
}

impl FusionEngine {
    pub fn new() -> Self {
        Self {
            processors: vec![
                Box::new(OrderbookMomentumProcessor),
                Box::new(SpikeDivergenceProcessor),
                // Future: add liquidity (poly-maker), AI edge (Poly-Trader), sentiment (agents/BTC), etc.
            ],
        }
    }

    /// Fuse signals for a market. Returns fused score + attribution map (for journal.metrics jsonb).
    /// In production: called from decision path after ingester tick; write to journal (see writer.rs pattern).
    pub fn fuse(
        &self,
        snapshot: &serde_json::Value,
        ctx: &serde_json::Value,
    ) -> Result<(Decimal, serde_json::Value)> {
        let mut total_weighted: Decimal = Decimal::ZERO;
        let mut total_weight: Decimal = Decimal::ZERO;
        let mut attribution = serde_json::Map::new();

        for p in &self.processors {
            match p.compute_signal(snapshot, ctx) {
                Ok(sig) => {
                    let w = sig.confidence; // weight by confidence (simple; future learned)
                    total_weighted += sig.score * w;
                    total_weight += w;
                    attribution.insert(
                        sig.processor_name.to_string(),
                        json!({
                            "score": sig.score,
                            "confidence": sig.confidence,
                            "edge": sig.edge,
                            "metadata": sig.metadata
                        }),
                    );
                }
                Err(e) => {
                    warn!(processor = %p.name(), error = %e, "processor failed (paper-only; degraded fusion)");
                    // No silent fallback (anti-pattern #5): attribution notes the failure.
                    attribution.insert(p.name().to_string(), json!({"error": e.to_string()}));
                }
            }
        }

        let fused = if total_weight > Decimal::ZERO {
            total_weighted / total_weight
        } else {
            Decimal::ZERO
        };

        let attr_json = serde_json::Value::Object(attribution);
        Ok((fused, attr_json))
    }

    /// Extended path exposing **net edge after fees/gas** (the primary signal for the deliberate
    /// 5-min Decision Report tier, per fees-tax-latency-and-execution-tiers.md + goals-and-operational-cadence.md).
    ///
    /// Builds on fuse() + adds fee costing + enriched attribution (no silent; errors noted).
    /// One path updated for smallest viable (this + example placeholder).
    ///
    /// fee_ctx: from PaperTradingEngine (or defaults). notional: approx USD size for costing.
    /// Returns (gross_fused, net_after_fees, enriched_attribution_json_for_journal).
    ///
    /// RISK (AGENTS + wiki): Net (not gross) is non-negotiable for $150 capital. Fees routinely
    /// destroy small edges. This must become the gate before any paper submit. Always journal the
    /// full attr (including fee_impact) so Hermes can do fee-adjusted per-signal attribution.
    /// Conservative bias in defaults. Paper-only.
    ///
    /// Credits: net-of-fees requirement + tier model from the two 2026-05-25 strategy wiki pages;
    /// fusion patterns from BTC-bot signal_fusion.py (extended for costs).
    pub fn fuse_net(
        &self,
        snapshot: &serde_json::Value,
        ctx: &serde_json::Value,
        fee_ctx: Option<&FeeContext>,
        notional: Decimal,
    ) -> Result<(Decimal, Decimal, serde_json::Value)> {
        let (gross, mut attribution) = self.fuse(snapshot, ctx)?;

        let (net, fee_note) = if let Some(f) = fee_ctx {
            let rate = f.taker_bps / dec!(10000); // conservative: assume taker for most opportunities
            let fees = (notional * rate) + f.est_gas_usdc
                - (notional * (f.rewards_offset_bps / dec!(10000)));
            let fees = fees.max(Decimal::ZERO);
            let n = gross - fees;

            // Enrich attribution (jsonb ready for journal; explicit, no silent)
            if let Some(map) = attribution.as_object_mut() {
                map.insert(
                    "fee_impact".to_string(),
                    json!({
                        "taker_bps_used": f.taker_bps.to_string(),
                        "est_fees_and_gas": fees.to_string(),
                        "notional_for_cost": notional.to_string(),
                        "gross_edge": gross.to_string(),
                        "net_edge_after_fees": n.to_string(),
                        "note": "PRIMARY signal for deliberate 5-min tier (see fees wiki + 4-6% min net in goals). Gross optimism fatal at small capital."
                    }),
                );
            }
            (n, "fee_ctx provided; net computed")
        } else {
            if let Some(map) = attribution.as_object_mut() {
                map.insert(
                    "fee_impact".to_string(),
                    json!({
                        "note": "no fee_ctx (degraded path); net == gross. Always provide real FeeContext from paper engine for production use.",
                        "gross_edge": gross.to_string()
                    }),
                );
            }
            (gross, "no fee_ctx; net=gross (degraded)")
        };

        // Also surface a DecisionReport-shaped view in attribution for downstream 5-min generators
        if let Some(map) = attribution.as_object_mut() {
            map.insert(
                "decision_report_summary".to_string(),
                json!({
                    "fused_gross_edge": gross.to_string(),
                    "net_edge_after_fees": net.to_string(),
                    "fee_note": fee_note,
                    "primary_for_deliberate_tier": true
                }),
            );
        }

        let attr_json = attribution; // already a Value (from inner fuse); mutated in place via as_object_mut when Object
        Ok((gross, net, attr_json))
    }
}

impl Default for FusionEngine {
    fn default() -> Self {
        Self::new()
    }
}

// Allow dead code in skeleton (will be wired/used in follow-up increments per plan; module-level #![allow] at top is sufficient and documented).
pub fn example_fuse_usage_placeholder() {
    // Example (not called yet; demonstrates journal hook using existing writer.rs patterns + new net edge path).
    // Proper handling (never unwrap; see fuse_net explicit fee_impact + error attribution; anti-pattern #5).
    // let engine = FusionEngine::new();
    // let fee = Some(FeeContext { taker_bps: dec!(100), ..Default::default() });
    // match engine.fuse_net(&json!({}), &json!({}), fee.as_ref(), dec!(5.0)) {
    //     Ok((gross, net, attr)) => {
    //         // DecisionReport-shaped (ready for 5-min generator + jsonb journal)
    //         let report = DecisionReport {
    //             fused_gross_edge: gross,
    //             net_edge_after_fees: net,
    //             confidence: dec!(0.6),
    //             attribution: attr,
    //         };
    //         // Later: journal ... (metrics or decision_context = serde_json::to_value(&report) )
    //         tracing::debug!(gross=%report.fused_gross_edge, net=%report.net_edge_after_fees, "net edge (primary deliberate signal) ready for journal");
    //     }
    //     Err(e) => { /* log and degrade */ }
    // }
    tracing::debug!("FusionEngine skeleton ready (paper-only, Decimal, net edge after fees + DecisionReport for deliberate tier + Hermes)");
}
